import Head from "next/head";

import Navbar from "./Navbar";
import Banner from "./Banner";
import Pricing from "./Pricing";
import Visas from "./Visas";

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen">
        <Navbar />
        <Banner />
        <Pricing />
        <Visas />
      </main>
    </div>
  );
}
